### ISSUE TITLE
Checklist of ODF 1.3 CS02 Enhancements

### ISSUE THREAD

**Issue by svanteschubert** [oasis-tcs/odf-tc#21]
- [x] C1 - Part 2 fixing two references by replacing in XML 'element-dsig:document-signatures' with 'attribute-manifest:version_element-dsig:document-signatures'
- [x] C2 - Part 2 removing accidental bookmarks 'pp', 'msg15', 'DDE_LINK1'
- [x] C3 - Part 2 exchanging four instances of 'implementation defined' with 'implemenation-defined' according to [Terminology](https://docs.oasis-open.org/office/OpenDocument/v1.3/cs01/part2-packages/OpenDocument-v1.3-cs01-part2-packages.html#__RefHeading__752779_826425813)
- [x] C4 - Part 2: Overriding font-height="100%" with font-height="normal" at our specs root style "Normal" 
- [x] C5 - Part 2: Fixing font color problem in HTML (part 1) by moving "Text Body" back from beyond "Abstract" to beyond "Normal" 
- [x] C6 - Part 2: Fixing font color problem in HTML (part 2) by resolving style hierarchy of title-page styles moving color in extra style
- [x] C7 - Part 2: Replacing [unallowed Text Style "Definition" with correct "Def" character style](https://github.com/oasis-tcs/odf-tc/blob/master/src/test/resources/odf1.3/tools/How_to_prepare_ODF_specification_documents.md#text-styles), see below
- [x] C8 - Part 2: Added 58 times character style 'ISO Keyword' to 'shall'/'shall not', see below
- [x] C9 - Part 2: Removed at the end (manually) three none-ODF XML attributes: draw:fill, draw:fill-color, draw:opacity
- [x] C10 - Part 4: Replacing 'implementation defined' with 'implementation-defined' according to Terminology
- [x] C11 - Part 1,3,4: Checked 'implementation dependent' with 'implementation-dependent' according to Terminology
- [x] C12 - Part 1,3,4: Font color and line-heigt adjustments for HTML
- [x] C13 - Moving ODT-HTML and XML-default-files into docs/odf1.3/ to be viewable with browser!
- [x] C14 - Part 2: Update reference of broken link: ANSI/NISO Z39.86-2005 (R2012)
- [x] C15 - Part 4: Update reference of broken link: https://www.iso.org/
- [x] C16 - Part 1,3,4: Removing at the end (manually) three none-ODF 1.2 XML attributes: draw:fill, draw:fill-color, draw:opacity
- [x] C17 - Part 3: Updating current default value XML of part3 to /docs directory
- [x] C18 - Part 1-4: HTML XSLT fix to cover all grey-boxed paragraph border issues 
- [x] C19 - Part 3: HTML XSLT have to use HTTPS reference to MathML (ignored in CS01 in Chrome)
- [x] C20 - Part 3: HTML using MathML JavaScript, CSS, etc. files from our GitHub Copy 
- [x] C21 - Part 1: Updated TC participants list
- [x] C22 - Part 1: Removed unused revision chapter
- [x] C23 - Part 1-4: Fixed Appendix headings in HTML (using h tag instead h1 to h3)
- [x] C24 - Part 1-4: Fixed Appendix headings removing trailing '.' added indent in between title
- [x] C25 - Part 1-4: Updated Table of Contents (ToC) manually via LibreOffice
- [x] C26 - Part 1,2: Table of Content (ToC) was in HTML without chapter numbers
- [x] C27 - Part 3: Regina found (and I removed) about a dozen duplicated text boxes in the appendices
 
*** Tasks for OASIS
- [x] I -  Part 1-4: Adding metadata to meta.xml that can be reused by HTML for search engines
- [x] II - Part 1-4: Exchanged OASIS voting date
- [x] III - Part 1-4: After a conference call with OASIS updated TC copyright header accordingly
- [x] IV - Part 1-4: Provided [ZIP with all our deliverables at OASIS](https://www.oasis-open.org/committees/document.php?document_id=67663&wg_abbrev=office) to vote upon,

Further tasks & issues were moved to ODF 1.4, see #27

**Regarding C7**: Documentation of allowed styles:
https://github.com/oasis-tcs/odf-tc/blob/master/src/test/resources/odf1.3/tools/How_to_prepare_ODF_specification_documents.md#text-styles

**Regarding C8**: Test reading is easier for the "shall" setting, by opening the HTML part 2 page and change the background colour of the "ISO Keyword" CSS style using the browser development tool (pressing F12 to open tooling).

***Validation:***
- Our ODT deliverable (part 1, 2, 3 and 4) was validated via https://odfvalidator.org/ 
*Note:* 
ODT Part 3 is invalid ODF 1.2 as TC's LibreOffice Version is using negative @fo:padding-top, only non-negative are allowed
ODT Part 3+4 are indicated as invalid as MathML has no grammar, this might be a validator issue (or LO issue)
- Our HTML deliverable (part 1, 2, 3 and 4) was checked for broken links via https://www.drlinkcheck.com/

**Comment by franciscave** [comment]
Not only should the text use (and highlight) the ISO keywords correctly, but should avoid alternative words that are deprecated by the ISO/IEC Directives Part 2. Thus, for example, in section 3.7, step 12, the use of “must” in the last sentence is deprecated, so should be replaced by “shall”.

But do we want to check all ISO keywords in Parts 3 Schema and 4 Formula? This is a big task (Patrick and I started work on this some weeks ago) and I would have thought it could be postponed to ODF 1.4.

**Comment by pdurusau** [comment]
Francis I'm not sure about the highlighting of ISO keywords. The latest version of ISO/IEC Directives Part 2, https://isotc.iso.org/livelink/livelink?func=ll&objId=4230456&objAction=browse&sort=subtype (8th edition), reserves bold for preferred terms. Section 7. 

Yes to correctiong "must" in part 2, Section 3.7, step 12; part 3, Annex D, D.3; part 4, 3.4, 11. I didn't find any other uses of must.

**Comment by franciscave** [comment]
Patrick, you're right to pick me up on this. I was using the term "highlighting" loosely. What I think is useful - I have found it useful - is to have the ISO keywords styled with the named character style 'ISO Keyword', so that it is easy to find all instances to verify that the terms are being used correctly. I should therefore have said "style" rather than "highlight". I should stress that this does not mean that the ISO keywords would be _distinctively_ styled. As you rightly point out, ISO house style in effect forbids this. But don't get me started on ISO house style... [in many respects they're living in the stone age].

**Comment by svanteschubert** [comment]
Seems I am not able to access the ISO/IEC Directives. 
You - who have access and are aware of ISO rules - have to be certain that we only "should" highlight and not "shall" highlight.
In general, it would be wise to move only 'allowed' defects to ODF 1.4, otherwise, the cost and time to fix them would only rise for us.

The exchange of words within our normative parts might be able to be automated, but I agree we should move as much as possible into ODF 1.4.

**Comment by franciscave** [comment]
The ISO/IEC Directives and other related resources can be found [here](https://isotc.iso.org/livelink/livelink?func=ll&objId=4230450&objAction=browse&sort=name&viewType=1).

ISO are less strict with PAS submissions than they are with standards developed by ISO and IEC committees. The current specifications are pretty close.

**Comment by svanteschubert** [comment]
Thanks, I just realized my browser used by default my CEN account, which
strangely did not work, although available for everyone else.
Using a different browser worked.

Am Sa., 15. Aug. 2020 um 21:59 Uhr schrieb Francis Cave <
notifications@github.com>:
